// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type InitialLaunchEmail struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Prayer struct {
	ID               uuid.UUID
	PrayerTitle      string
	PrayerRequest    string
	Category         string
	RelatedScripture sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsAnonymous      bool
	UserID           uuid.UUID
}

type PrayerComment struct {
	ID          uuid.UUID
	PrayerID    uuid.UUID
	Comment     string
	CommenterID uuid.UUID
	IsAnonymous bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PrayerResponse struct {
	ID        uuid.UUID
	PrayerID  uuid.UUID
	UserID    uuid.UUID
	Status    string
	Hidden    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	ClerkID   string
	Email     string
	Username  string
	AvatarSrc string
	CreatedAt time.Time
	UpdatedAt time.Time
}
